# Generated by Django 5.2.3 on 2025-07-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_buyer_alter_order_status'),
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        
    ]
