# Generated by Django 5.2.3 on 2025-07-20 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_appuser'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratetrader',
            name='buyer',  
        ),
        migrations.AddField(
            model_name='ratetrader',
            name='buyer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='buyer_ratings',
                to='authentication.appuser',
                null=True, 
            ),
        ),
        migrations.RemoveField(
            model_name='ratetrader',
            name='seller',
        ),
        migrations.AddField(
            model_name='ratetrader',
            name='seller',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='seller_ratings',
                to='authentication.appuser',
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name='review',
            name='buyer',
        ),
        migrations.AddField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='authentication.appuser',
                null=True,
            ),
        ),
    ]