# Generated by Django 5.2.3 on 2025-07-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_appuser_user'),
        ('reviews', '0003_alter_ratetrader_buyer_alter_ratetrader_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetrader',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_ratings', to='authentication.appuser'),
        ),
        migrations.AlterField(
            model_name='ratetrader',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_ratings', to='authentication.appuser'),
        ),
        migrations.AlterField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.appuser'),
        ),
    ]
