# Generated by Django 5.2.3 on 2025-07-19 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='email_or_phone_check')],
            },
        ),
    ]
