# Generated by Django 5.2.3 on 2025-07-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_appuser'),
        ('orders', '0002_alter_order_buyer'),
        ('product', '0002_alter_product_user'),
        ('reviews', '0002_alter_ratetrader_buyer_alter_ratetrader_seller_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='appuser_email_or_phone_check'),
        ),
    ]
