# Generated by Django 5.2.3 on 2025-07-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='carts', to='cart.cartitem'),
        ),
    ]
