# Generated by Django 5.2.3 on 2025-07-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='buyer',
        ),
    ]
