# Generated by Django 5.2.3 on 2025-07-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_appuser_user'),
        ('orders', '0006_order_product_order_quantity_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authentication.appuser'),
        ),
    ]
